<a href="https://colab.research.google.com/github/Chiragks-1/mlops-zoomcamp/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
import pickle
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

from sklearn.metrics import mean_squared_error

In [6]:
df = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-02.parquet')

In [7]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2022-02-01 00:20:21,2022-02-01 00:24:30,N,1.0,43,238,1.0,1.16,5.50,0.5,0.5,1.02,0.0,None,0.3,7.82,1.0,1.0,0.00
1,2,2022-02-01 00:32:26,2022-02-01 00:35:31,N,1.0,166,24,1.0,0.57,4.50,0.5,0.5,0.00,0.0,None,0.3,5.80,2.0,1.0,0.00
2,1,2022-02-01 00:17:27,2022-02-01 00:44:44,N,1.0,226,219,1.0,0.00,42.20,0.0,0.5,0.00,0.0,None,0.3,43.00,1.0,1.0,0.00
3,2,2022-02-01 00:45:37,2022-02-01 01:27:16,N,1.0,89,83,1.0,16.62,49.00,0.5,0.5,0.00,0.0,None,0.3,50.30,2.0,1.0,0.00
4,2,2022-02-01 00:06:46,2022-02-01 00:30:06,N,1.0,7,238,1.0,5.97,21.00,0.5,0.5,4.50,0.0,None,0.3,29.55,1.0,1.0,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69394,2,2022-02-28 23:27:00,2022-02-28 23:38:00,None,NaN,65,87,NaN,2.61,13.60,0.0,0.0,3.66,0.0,None,0.3,20.31,NaN,NaN,NaN
69395,2,2022-02-28 23:59:00,2022-03-01 00:10:00,None,NaN,97,231,NaN,2.88,12.07,0.0,0.0,3.00,0.0,None,0.3,18.12,NaN,NaN,NaN
69396,2,2022-02-28 23:18:00,2022-02-28 23:27:00,None,NaN,74,116,NaN,2.22,10.68,0.0,0.0,1.22,0.0,None,0.3,12.20,NaN,NaN,NaN
69397,2,2022-02-28 23:31:00,2022-02-28 23:39:00,None,NaN,42,69,NaN,1.59,8.88,0.0,0.0,0.00,0.0,None,0.3,9.18,NaN,NaN,NaN
69398,2,2022-02-28 23:14:00,2022-02-28 23:35:00,None,NaN,243,100,NaN,8.16,27.74,0.0,0.0,6.79,0.0,None,0.3,37.58,NaN,NaN,NaN

In [8]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [9]:
df['duration'] = df.lpep_dropoff_datetime - df.lpep_pickup_datetime

In [10]:
df.duration = df.duration.apply(lambda td: td.total_seconds()/60)

In [11]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,duration
0,2,2022-02-01 00:20:21,2022-02-01 00:24:30,N,1.0,43,238,1.0,1.16,5.50,...,0.5,1.02,0.0,None,0.3,7.82,1.0,1.0,0.00,4.150000
1,2,2022-02-01 00:32:26,2022-02-01 00:35:31,N,1.0,166,24,1.0,0.57,4.50,...,0.5,0.00,0.0,None,0.3,5.80,2.0,1.0,0.00,3.083333
2,1,2022-02-01 00:17:27,2022-02-01 00:44:44,N,1.0,226,219,1.0,0.00,42.20,...,0.5,0.00,0.0,None,0.3,43.00,1.0,1.0,0.00,27.283333
3,2,2022-02-01 00:45:37,2022-02-01 01:27:16,N,1.0,89,83,1.0,16.62,49.00,...,0.5,0.00,0.0,None,0.3,50.30,2.0,1.0,0.00,41.650000
4,2,2022-02-01 00:06:46,2022-02-01 00:30:06,N,1.0,7,238,1.0,5.97,21.00,...,0.5,4.50,0.0,None,0.3,29.55,1.0,1.0,2.75,23.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69394,2,2022-02-28 23:27:00,2022-02-28 23:38:00,None,NaN,65,87,NaN,2.61,13.60,...,0.0,3.66,0.0,None,0.3,20.31,NaN,NaN,NaN,11.000000
69395,2,2022-02-28 23:59:00,2022-03-01 00:10:00,None,NaN,97,231,NaN,2.88,12.07,...,0.0,3.00,0.0,None,0.3,18.12,NaN,NaN,NaN,11.000000
69396,2,2022-02-28 23:18:00,2022-02-28 23:27:00,None,NaN,74,116,NaN,2.22,10.68,...,0.0,1.22,0.0,None,0.3,12.20,NaN,NaN,NaN,9.000000
69397,2,2022-02-28 23:31:00,2022-02-28 23:39:00,None,NaN,42,69,NaN,1.59,8.88,...,0.0,0.00,0.0,None,0.3,9.18,NaN,NaN,NaN,8.000000
69398,2,2022-02-28 23:14:00,2022-02-28 23:35:00,None,NaN,243,100,NaN,8.16,27.74,...,0.0,6.79,0.0,None,0.3,37.58,NaN,NaN,NaN,21.000000

In [12]:
df = df[df.trip_type==2]

In [13]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,duration
5,2,2022-02-01 00:26:19,2022-02-01 00:26:28,N,5.0,197,197,1.0,0.00,8.0,...,0.0,0.00,0.0,None,0.3,8.30,1.0,2.0,0.00,0.150000
30,2,2022-02-01 01:06:21,2022-02-01 01:15:30,N,5.0,92,192,1.0,2.48,15.0,...,0.0,4.59,0.0,None,0.3,19.89,1.0,2.0,0.00,9.150000
32,2,2022-01-31 15:11:04,2022-01-31 15:11:08,N,5.0,42,42,1.0,0.00,11.0,...,0.0,0.00,0.0,None,0.3,11.30,1.0,2.0,0.00,0.066667
87,2,2022-02-01 06:19:39,2022-02-01 06:47:56,N,5.0,129,239,1.0,6.63,40.0,...,0.0,0.00,0.0,None,0.3,43.05,2.0,2.0,2.75,28.283333
92,2,2022-02-01 06:59:54,2022-02-01 07:00:25,N,5.0,132,132,1.0,0.00,46.0,...,0.0,0.00,0.0,None,0.3,46.30,2.0,2.0,0.00,0.516667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61913,2,2022-02-28 22:54:22,2022-02-28 22:54:46,N,5.0,171,171,1.0,0.00,10.0,...,0.0,2.06,0.0,None,0.3,12.36,1.0,2.0,0.00,0.400000
61924,2,2022-02-28 22:53:20,2022-02-28 22:54:10,N,5.0,94,264,1.0,0.00,50.0,...,0.0,0.00,0.0,None,0.3,50.30,1.0,2.0,0.00,0.833333
61942,2,2022-02-28 22:05:50,2022-02-28 22:26:32,N,5.0,181,186,1.0,5.31,75.0,...,0.0,2.50,0.0,None,0.3,80.55,1.0,2.0,2.75,20.700000
61944,2,2022-02-28 22:05:33,2022-02-28 22:05:43,N,5.0,177,177,1.0,0.08,25.0,...,0.0,0.00,0.0,None,0.3,25.30,1.0,2.0,0.00,0.166667
61977,2,2022-02-28 23:47:57,2022-02-28 23:48:11,N,5.0,95,95,1.0,0.00,30.0,...,0.0,7.58,0.0,None,0.3,37.88,1.0,2.0,0.00,0.233333

In [14]:
df.duration.describe()

count    2627.000000
mean       17.806484
std        86.340650
min         0.000000
25%         0.100000
50%         4.600000
75%        14.883333
max      1436.650000
Name: duration, dtype: float64

In [15]:
df = df[(df.duration >= 1) & (df.duration <= 60)]

In [16]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,duration
30,2,2022-02-01 01:06:21,2022-02-01 01:15:30,N,5.0,92,192,1.0,2.48,15.0,...,0.0,4.59,0.0,None,0.3,19.89,1.0,2.0,0.00,9.150000
87,2,2022-02-01 06:19:39,2022-02-01 06:47:56,N,5.0,129,239,1.0,6.63,40.0,...,0.0,0.00,0.0,None,0.3,43.05,2.0,2.0,2.75,28.283333
217,2,2022-02-01 07:45:22,2022-02-01 07:55:15,N,1.0,74,42,1.0,1.09,8.0,...,0.5,0.00,0.0,None,0.3,8.80,2.0,2.0,0.00,9.883333
329,2,2022-02-01 08:48:40,2022-02-01 09:01:05,N,5.0,159,119,1.0,2.05,12.0,...,0.0,0.00,0.0,None,0.3,12.30,1.0,2.0,0.00,12.416667
526,2,2022-02-01 10:14:31,2022-02-01 10:37:45,N,5.0,242,132,1.0,15.94,65.0,...,0.0,0.00,0.0,None,0.3,65.30,2.0,2.0,0.00,23.233333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61788,2,2022-02-28 21:03:04,2022-02-28 21:21:59,N,5.0,75,68,1.0,4.47,27.0,...,0.0,9.02,0.0,None,0.3,39.07,1.0,2.0,2.75,18.916667
61804,2,2022-02-28 21:10:15,2022-02-28 21:39:48,N,5.0,7,188,1.0,12.64,40.0,...,0.0,0.00,0.0,None,0.3,40.30,1.0,2.0,0.00,29.550000
61842,2,2022-02-28 21:51:08,2022-02-28 22:05:18,N,5.0,92,132,1.0,8.94,30.0,...,0.0,2.80,0.0,None,0.3,33.10,1.0,2.0,0.00,14.166667
61845,2,2022-02-28 21:20:29,2022-02-28 21:42:41,N,5.0,78,41,2.0,6.79,20.0,...,0.0,0.00,0.0,None,0.3,20.30,2.0,2.0,0.00,22.200000
61942,2,2022-02-28 22:05:50,2022-02-28 22:26:32,N,5.0,181,186,1.0,5.31,75.0,...,0.0,2.50,0.0,None,0.3,80.55,1.0,2.0,2.75,20.700000

In [26]:
categorical = ['PULocationID', 'DOLocationID']

In [27]:
df[categorical] = df[categorical].astype(str)

<ipython-input-27-b20b27b908cf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[categorical] = df[categorical].astype(str)